import os

ext = {
    '0001':'webp','0002':'webp','0003':'webp','0004':'jpg','0005':'jpg',
    '0006':'webp','0007':'webp','0008':'webp','0009':'webp','0010':'webp',
    '0011':'webp','0012':'webp','0013':'webp','0014':'jpg','0015':'jpg',
    '0016':'jpg','0017':'jpg','0018':'webp','0019':'webp','0020':'jpg',
    '0021':'jpg','0022':'jpg','0023':'jpg','0024':'jpg','0025':'jpg',
    '0026':'jpg','0027':'jpg','0028':'jpg','0029':'jpg','0030':'jpg',
    '0031':'jpg','0032':'jpg','0033':'jpg','0034':'jpg','0035':'jpg',
    '0036':'jpg','0037':'webp','0038':'webp','0039':'webp','0040':'webp',
    '0041':'webp','0042':'webp','0043':'webp','0044':'webp','0045':'webp',
    '0046':'webp','0047':'jpg','0048':'webp','0049':'webp','0050':'webp',
    '0051':'webp','0052':'webp','0053':'webp','0054':'webp','0055':'webp',
    '0056':'webp','0057':'webp','0058':'webp','0059':'webp','0060':'webp',
    '0061':'webp','0062':'webp','0063':'webp','0064':'webp','0065':'webp',
    '0066':'webp','0067':'webp','0068':'webp','0069':'webp','0070':'webp',
    '0071':'webp','0072':'webp','0073':'webp','0074':'webp','0075':'webp',
    '0076':'webp','0077':'webp','0078':'webp','0079':'webp','0080':'webp',
    '0081':'webp','0082':'webp','0083':'webp','0084':'webp','0085':'webp',
    '0086':'webp','0087':'webp','0088':'webp','0089':'webp','0090':'webp',
    '0091':'webp','0092':'webp','0093':'webp','0094':'webp','0095':'webp',
    '0096':'webp','0097':'webp','0098':'webp','0099':'webp','0100':'jpg',
    '0101':'webp','0102':'jpg','0103':'jpg','0104':'jpg','0105':'jpg',
    '0106':'jpg','0107':'jpg','0108':'jpg','0109':'jpg','0110':'jpg',
    '0111':'jpg','0112':'jpg','0113':'jpg','0114':'jpg','0115':'jpg',
    '0116':'webp','0117':'webp','0118':'webp','0119':'webp','0120':'webp',
    '0121':'webp','0122':'webp','0123':'webp','0124':'webp','0125':'jpg',
    '0126':'jpg','0127':'webp','0128':'webp','0129':'webp','0130':'webp',
    '0131':'webp','0132':'webp','0133':'webp','0134':'webp','0135':'webp',
    '0136':'webp','0137':'webp','0138':'webp','0139':'webp','0140':'webp',
    '0141':'webp','0142':'webp','0143':'webp','0144':'webp','0145':'webp',
    '0146':'webp','0147':'webp','0148':'webp','0149':'webp','0150':'webp',
    '0151':'webp','0152':'webp','0153':'webp','0154':'webp','0155':'webp',
    '0156':'webp','0157':'webp','0158':'webp','0159':'jpg','0160':'webp'
}

html = ''
for i, key in enumerate(ext.keys()):
    html += f'      <div class="g-item" data-index="{i}" onclick="openLb({i})"><img src="/gallery/images/{key}.{ext[key]}" loading="lazy" decoding="async" alt="Photo {i+1}"></div>\n'

with open('gallery/index.html', 'r', encoding='utf-8') as f:
    content = f.read()

content = content.replace('<!-- Images generated by JS below to keep HTML lean -->', html)

# Remove the JS generation logic from gallery index.html
import re
# We just need to replace the part that dynamically creates the grid
# Since I wrote it, I know it looks like `var imgs = nums.map...` and `imgs.forEach...`
# Let's just remove the JS from gallery/index.html entirely that does grid generation, but keep openLb.
# Wait, let's just rewrite the script section of gallery/index.html
script_part = """<script>
(function () {
  var ext = {""" + ", ".join([f"'{k}':'{v}'" for k, v in ext.items()]) + """};
  var nums = Object.keys(ext);
  var imgs = nums.map(function(n){ return '/gallery/images/' + n + '.' + ext[n]; });

  var lb = document.getElementById('lb');
  var lbImg = document.getElementById('lb-img');
  var cur = 0;

  window.openLb = function(i) {
    cur = i;
    lbImg.src = imgs[i];
    lb.classList.add('open');
    document.body.style.overflow = 'hidden';
  }

  function closeLb() {
    lb.classList.remove('open');
    document.body.style.overflow = '';
    lbImg.src = '';
  }

  document.getElementById('lb-close').addEventListener('click', closeLb);
  document.getElementById('lb-prev').addEventListener('click', function(){
    cur = (cur - 1 + imgs.length) % imgs.length;
    lbImg.src = imgs[cur];
  });
  document.getElementById('lb-next').addEventListener('click', function(){
    cur = (cur + 1) % imgs.length;
    lbImg.src = imgs[cur];
  });

  lb.addEventListener('click', function(e){
    if (e.target === lb) closeLb();
  });

  document.addEventListener('keydown', function(e){
    if (!lb.classList.contains('open')) return;
    if (e.key === 'Escape') closeLb();
    if (e.key === 'ArrowLeft') { cur = (cur - 1 + imgs.length) % imgs.length; lbImg.src = imgs[cur]; }
    if (e.key === 'ArrowRight') { cur = (cur + 1) % imgs.length; lbImg.src = imgs[cur]; }
  });
})();
</script>"""

# Replace the whole <script>...</script> at the bottom.
content = re.sub(r'<script>\n\(function \(\) \{\n\s+// Build image list.*?</script>', script_part, content, flags=re.DOTALL)

with open('gallery/index.html', 'w', encoding='utf-8') as f:
    f.write(content)
